title: Covid configuration example

activity_to_super_groups:
  primary_activity: ['schools', 'companies', "universities"]
  leisure: ['pubs', 'cinemas', 'groceries', "care_home_visits", "household_visits"] 
  residence: ['households', 'care_homes']
  commute : ['city_transports', 'inter_city_transports']
  medical_facility: ['hospitals']

time:
  total_days:  5 
  initial_day: "2020-02-28" 
  step_duration: 
      weekday:
          0: 1 
          1: 8
          2: 1
          3: 3
          4: 11
      weekend:
          0: 4 
          1: 4 
          2: 4 
          3: 12 
  step_activities:
      weekday:
          0: ['medical_facility', 'commute', 'residence'] 
          1: ['medical_facility', 'primary_activity', 'leisure', 'residence'] 
          2: ['medical_facility', 'commute', 'residence'] 
          3: ['medical_facility', 'leisure', 'residence']
          4: ['medical_facility', 'residence']
      weekend:
          0: ['medical_facility', 'leisure', 'residence']
          1: ['medical_facility', 'leisure', 'residence']
          2: ['medical_facility', 'leisure', 'residence']
          3: ['medical_facility', 'residence']


# note we currently do not save checkpoints for memroy reasons
checkpoint_dates:
  2020-05-06
  2020-07-01
  2020-08-30
