#!/bin/bash --login
# On Archer you probably can't run the setup on the login node because of 
# MPI import problems. However, you can build the setup using this simple script
#PBS -N june
#PBS -l select=1
#PBS -l walltime=0:5:0
#PBS -A n02-cms
#PBS -q short

conda activate junew
echo `which python`

cd /work/n02/n02/bnl/june/june_runs

echo `pwd`

aprun -n 1 python run_simulation.py --setup run_configs/northwest_beyonce_archer.yaml

