system_configuration:
  name: cosma #available : [cosma, jasmin]
  queue: cosma6
  account: dp004 
  jobs_per_node: 4
  parallel_tasks_path: "default"
  runner_path: "default"
  email_notifications: no
  email_address: null # your email here
  verbose: yes
  max_time: "72:00:00"
  
region: "london"
iteration: 1

paths_configuration: # use @ as placeholder
  base_path: "/cosma6/data/dp004/dc-cues1/june_runs"
  world_path: "/cosma6/data/dp004/dc-cues1/JUNE/scripts/tests.hdf5"
  results_path: "@base_path/adam"
  summary_path: "@results_path/summaries" # note the different "base"!
  stdout_path: "default"
  config_path: "@base_path/config.yaml"

infection_configuration:
  infectivity_profile: "XNExp" # available: ["XNExp", "nature", "correction_nature"]

policy_configuration:
  lockdown_ratio: 0.5

parameter_configuration:
  iteration: 1
  parameters_to_run: [0,1,2,3]
  # number_of_samples: 250 # irrelevant here, as running a grid.
  config_type: "file"
  parameters_to_vary:
    path: "/cosma6/data/dp004/dc-cues1/june_runs/sample_parameters.csv" 
# can also provide fixed parameters as dict like policy_configuration

summary_configuration:
  'age_bins' : [0, 6, 18, 65, 85, 100]











