system_configuration:
  name: "cosma" #available : [cosma, jasmin]

paths_configuration: # use @ as placeholder
  base_path: "/cosma6/data/dp004/dc-quer1/june_runs"
  world_path: "@base_path/../june_worlds"
  results_path: "@base_path/june_results"
  config_path: "@base_path/config.yaml"

infection_configuration:
  infectivity_profile: "xnexp" # available: ["xnexp", "nature", "correction_nature"]

region_configuration:
  name: "london"

parameter_configuration:
  iteration: 1
  number_of_variations: 250
  method: "latin_hypercube"
  parameters_to_vary:
    betas:
      beta_overall_rescaling: 1
      'pub'       : (0.01, 0.25)
      'grocery'   : (0.01, 0.25)
      'cinema'    : (0.01, 0.25)
      'commute_unit' : (0.01, 0.5)
      'commute_city_unit' : (0.01, 0.5)
      'hospital'  : (0.05, 0.5)
      'care_home' : (0.05, 1.)
      'company'   : (0.05, 0.5)
      'school'    : (0.05, 0.5)
      'household' : (0.05, 0.5)
      'university': (0.01, 0.5)
      'alpha_physical' : (1.8,3.0)

    asymptomatic_ratio: (0.05,0.4)
    seeding:
      'seed_strength' : (0.5,1.3),
    policies:
      social_distancing:
        1: 
          beta_factor: "auto"
        2:
          beta_factor: (0.3,0.9)
      quarantine:
        1:
          household_compliance: "auto"
        2: 
          household_compliance: (0.2,0.8)
